# Generated by Django 2.2.10 on 2021-09-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text_type',
            new_name='question_type',
        ),
        migrations.AlterField(
            model_name='polling',
            name='start_date',
            field=models.DateTimeField(editable=False),
        ),
    ]
