# Generated by Django 2.2.10 on 2021-09-12 16:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210912_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 12, 16, 53, 49, 865823, tzinfo=utc), editable=False),
        ),
    ]
