# Generated by Django 2.2.10 on 2021-09-12 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210912_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 12, 16, 55, 3, 610807, tzinfo=utc), editable=False),
        ),
    ]
